modules:
  - type: rpm-ostree   
    install:
        - jetbrains-mono-fonts-all
        - fira-code-fonts
        - langpacks-id
  - type: fonts
    fonts:
      nerd-fonts:
        - Agave
        - UbuntuMono
      google-fonts:
        - Plus Jakarta Sans
