modules:
  - type: script # setup container and cleanup
    scripts:
    - container-setup.sh
    - after-build.sh
  - type: signing # this sets up the proper policy & signing files for signed images to work fully