  - type: script 
    scripts:
        - after-build.sh
  - type: containerfile
    snippets:     
        - RUN rm -f /etc/yum.repos.d/vscode.repo && \
              rm -f /etc/yum.repos.d/docker-ce.repo && \
              rm -f /etc/yum.repos.d/unityhub.repo && \
              rm -f /etc/yum.repos.d/hardware:razer.repo 
