modules:
  - type: rpm-ostree  
    snippets:
        - COPY --from=ghcr.io/ublue-os/akmods:main-39 /rpms /tmp/akmods-rpms
        - RUN rpm-ostree install /tmp/akmods-rpms/kmods/*openrazer*.rpm
    repos:
        - https://download.docker.com/linux/fedora/docker-ce.repo
        - https://raw.githubusercontent.com/ublue-os/bluefin/main/dx/etc/yum.repos.d/vscode.repo
        - https://download.opensuse.org/repositories/hardware:/razer/Fedora_39/hardware:razer.repo
    install:
                - docker-ce
                - docker-ce-cli
                - docker-buildx-plugin
                - docker-compose-plugin
                - code
                - neofetch
                - zsh
                - openrazer-daemon
                - yt-dlp
                - jetbrains-mono-fonts-all
                - polychromatic
                - python3-openrazer
                - fira-code-fonts
    remove:
                - firefox # default firefox removed in favor of flatpak
                - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
