modules:
  - type: containerfile   
    snippets:
        - COPY --from=ghcr.io/ublue-os/akmods:main-39 /rpms /tmp/akmods-rpms
        - RUN rpm-ostree install /tmp/akmods-rpms/kmods/*openrazer*.rpm
        - RUN curl -Lo /tmp/starship.tar.gz "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz" && \
          tar -xzf /tmp/starship.tar.gz -C /tmp && \
          install -c -m 0755 /tmp/starship /usr/bin 