# image name
name: kodingers-gnome

# image description
description: kodingers os with gnome.

# base image
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # version

# module configuration
modules:
    - from-file: container.yml
    - from-file: package.yml
    - from-file: after-build.yml

-type: signing # this sets up the proper policy & signing files for signed images to work fully

