modules:
  - type: rpm-ostree  
    install:
        - labwc
        - labwc-menu-generator
        - flatpak
        - waybar
        - wofi
        - wl-randr
        - grim
        - slurp
        - lightdm
        - slick-greeter
