modules:
  - type: rpm-ostree  
    install:
        - labwc
        - labwc-menu-generator
        - flatpak
        - waybar
        - wofi
        - grim
        - slurp
        - greetd
        - greetd-selinux
        - pcmanfm
        - foot
        - xorg-x11-server-Xwayland 
  - type: containerfile   
    snippets:
        - RUN systemctl enable greetd
    
