modules:
  - type: files
    files:
        - etc: /etc
  - type: rpm-ostree  
    install:
        - labwc
        - labwc-menu-generator
        - flatpak
        - waybar
        - wofi
        - grim
        - slurp
        - lightdm
        - slick-greeter
        - pcmanfm
        - foot
        - xorg-x11-server-Xwayland 

  - type: systemd
    system:
        enabled:
          - lightdm.service 
          - ublue-lightdm-workaround.service

