modules:
  - type: script
    scripts:
      - setup-google-chrome-repo.sh
  - type: rpm-ostree  
    repos:
        - https://gist.githubusercontent.com/sekalengrengginang/8673e3f71d913c1d384bf8a64af8df1c/raw/cf904a36c5bea766ef5145d9d8605009be419d88/unityhub.repo
    install:
        - unityhub
    optfix:
        - unityhub # This is the directory being fixed, not the package name

 