modules:
  - type: rpm-ostree  
    install:
        - labwc
        - labwc-menu-generator
        - flatpak
        - waybar
        - wofi
        - grim
        - slurp
        - lightdm
        - slick-greeter
        - pcmanfm
        - foot
  - type: containerfile   
    snippets:
        - RUN systemctl enable lightdm
    
