# image name
name: kodingers-kde

# image description
description: kodingers os with kde.

# base image
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # version

# module configuration
modules:
    - from-file: openrazer-kmod.yml
    - from-file: configure-app.yml

type: script # setup container and cleanup
scripts:
        - container-setup.sh
        - after-build.sh
-type: signing # this sets up the proper policy & signing files for signed images to work fully

