# image name
name: kodingers-kde

# image description
description: kodingers os with kde.

# base image
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # version

# module configuration
modules:
    - from-file: remove-package.yml
    - from-file: openrazer.yml
    - from-file: add-package.yml
    - from-file: after-build.yml

-type: signing # this sets up the proper policy & signing files for signed images to work fully

