# image name
name: kodingers-labwc
# image description
description: labwc experiment

# base image
base-image: ghcr.io/ublue-os/base-main
image-version: latest # version

# module configuration
modules:
    - from-file: install-labwc.yml
    - from-file: after-build.yml
