# image name
name: kodingers-labwc
# image description
description: labwc experiment

# base image
base-image: quay.io/fedora-ostree-desktops/base
image-version: 39 # version

# module configuration
modules:
    - from-file: install-labwc.yml
-type: signing # this sets up the proper policy & signing files for signed images to work fully



