# image name
name: kodingers-laptop

# image description
description: kodingers os for my laptop.

# base image
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 40 # version

# module configuration
modules:
    - from-file: package.yml
    - from-file: after-build.yml

-type: signing # this sets up the proper policy & signing files for signed images to work fully

