modules:
  - type: containerfile   
    snippets:
        - COPY --from=ghcr.io/ublue-os/akmods:main-39 /rpms /tmp/akmods-rpms
        - RUN rpm-ostree install /tmp/akmods-rpms/kmods/*openrazer*.rpm
  - type: rpm-ostree   
    repos:
          - https://download.opensuse.org/repositories/hardware:/razer/Fedora_39/hardware:razer.repo
    install:
            - openrazer-daemon
            - polychromatic
            - python3-openrazer