modules:
  - type: akmods
    install:
    - openrazer
  - type: rpm-ostree   
    repos:
          - https://download.opensuse.org/repositories/hardware:/razer/Fedora_39/hardware:razer.repo
    install:
            - openrazer-daemon
            - polychromatic
            - python3-openrazer