modules:
  - type: rpm-ostree   
    install:
        - qemu-char-spice
        - qemu-device-display-virtio-gpu
        - qemu-device-display-virtio-vga
        - qemu-device-usb-redirect
        - qemu-img
        - qemu-system-x86-core
        - qemu-user-binfmt
        - qemu-user-static
        - qemu
        - virt-manager